# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: jamiedubs.com
    url: https://www.jamiedubs.com
  - name: Blackbook
    url: https://000000book.com
  - name: Gawds
    url: https://www.gawds.xyz
  - name: Void Runners
    url: https://voidrunners.io
  - name: Star Wars Uncut
    url: https://www.starwarsuncut.com
  - name: RickrollDB
    url: https://rickrolldb.com/
  - name: Occupy Internet
    # url: https://occupyinter.net
    url: http://occupyinter.net
  - name: fffff.at
    url: http://fffff.at
  # - name: Homelab
  #   url: $HOMELAB_URL

assignees:
  - jamiew

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jamiedubs.com
  # baseUrl: /upptime
  name: Dubnet Status Tracker
  theme: day
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "Is it up?"
  introMessage: "Uptime monitoring for some web applications I've built or contributed to. Powered by [Upptime](https://github.com/upptime/upptime)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
