# Change these first
owner: jamiew
repo: uptime-monitor

sites:
  - name: jamiedubs.com
    url: https://www.jamiedubs.com
  - name: Blackbook
    url: https://000000book.com
  - name: Gawds
    url: https://www.gawds.xyz
  - name: Void Runners
    url: https://voidrunners.io
  - name: DefDAO
    url: https://www.defdao.xyz
  - name: Star Wars Uncut
    url: https://www.starwarsuncut.com
  - name: RickrollDB
    url: https://rickrolldb.com/
  - name: Occupy Internet
    # url: https://occupyinter.net
    url: http://occupyinter.net
  - name: fffff.at
    url: https://fffff.at

assignees:
  - jamiew

status-website:
  cname: status.jamiedubs.com
  # baseUrl: /upptime
  name: status.jamiedubs.com
  theme: light
  logoUrl: https://jamiedubs.com/images/mudkips/mudkip_is_astounded3-sm-transparent.png
  introTitle: "Nothing to see here"
  introMessage: "Uptime monitoring for web applications I've built or contributed to. Powered by [Upptime](https://github.com/upptime/upptime) and GitHub Actions"
  navbar:
    - title: Home
      href: https://jamiedubs.com
    - title: Status
      href: /
    - title: Repo
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
